### PR TITLE
Updating the documentation and examples for IngressLink support

### PR DESCRIPTION
**Pull request by vklohiya**
**Description**:  _Add Issue/Feature description_

**Changes Proposed in PR**:

**Fixes**: #_Github issue id_

## General Checklist
- [x] Updated Added functionality/ bug fix in release notes

### CODE REVIEW

**Comment by srivastavnitin24** [comment]
looks good

**Review by srivastavnitin24 — APPROVED** [review]
looks good

**Review by vivek111585 — APPROVED** [review]
Looks fine

**Comment by vklohiya** [comment]
It was created just to test azure pipeline. Closing the pull request.

**Pull request closed without merging**
