### PR TITLE
Fix bug wrong virtual deletion

### PR DESCRIPTION
**Pull request by arzzon**
**Description**:  Fix bug wrong virtual deletion.

**Changes Proposed in PR**: Fix bug wrong virtual deletion.

**Fixes**: resolves #_Github issue id_

## General Checklist
- [ ] Updated Added functionality/ bug fix in release notes

### CODE REVIEW

**Review by sravyap135 — APPROVED** [review]

**Comment by arzzon** [comment]
Already resolved with another PR.

**Pull request closed without merging**
