### PR TITLE
Fix issue 2164 debug log level issue.

### LINKED ISSUE #2164: Setting into DEBUG level, configmap does not get configured onto bigip, setting to INFO level seems to be working although a little slow.
#### Setup Details
 CIS Version : 2.7     
 Build: f5networks/k8s-bigip-ctlr:2.7.0     
 BIGIP Version: Big IP 14.1.2      
      
 Agent Mode: CCCL       
 Orchestration: K8S      
 Orchestration Version:       
 Pool Mode: Cluster      
 Additional Setup details: <Platform/CNI Plugins/ cluster nodes/ etc>

#### Description  
  - args:
- --bigip-username=$(BIGIP_USERNAME)
- --bigip-password=$(BIGIP_PASSWORD)
- --bigip-url=https://XXXXX:8443
- --insecure=true
- --bigip-partition=kubernetes
- --pool-member-type=cluster
- --flannel-name=/Common/fl-tunnel
- --agent=cccl
- --namespace=default
- --verify-interval=45
- --node-poll-interval=120
- --http-listen-address=0.0.0.0:9113
- --periodic-sync-interval=180
- --log-level=DEBUG
- --cccl-log-level=DEBUG

#### Steps To Reproduce
- have already got ~200 iapps 
- create a new configmap for iapp , it is not configured onto bigip
(is not signaling bigip,  config handler is not woken for reset) although the new iapp is written into config.json .

#### Expected Result 
configurations gets set onto bigip.

#### Actual Result  
it is not configured onto bigip. setting log to INFO level seems to be ok, though slow.

#### Diagnostic Information
```buildoutcfg
<Configuration files, error messages, logs>
Note: Sanitize the data. For example, be mindful of IPs, ports, application names and URLs
Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137
```  

#### Observations (if any)
(is not signaling bigip,  config handler is not woken for reset) although the new iapp is already written into config.json .

### PR DESCRIPTION
**Pull request by zongzw**
**Description**:  

Fix issue https://github.com/F5Networks/k8s-bigip-ctlr/issues/2164

**Changes Proposed in PR**:

The idea is enlarging the scanner buffer to double when the scanner fails to handle the large log message(with `ErrTooLong` reported).

**Fixes**: resolves #2164 

## General Checklist

- [x] Smoke testing completed

### CODE REVIEW

**Comment by trinaths** [comment]
Created [CONTCNTR-3138] for internal tracking.

**Review by vklohiya — APPROVED** [review]
LGTM

**Pull request merged**
