### PR TITLE
Chart automation

### PR DESCRIPTION
**Pull request by vklohiya**
**Description**:  Chart automation for testing and release. Operator automation for testing only.

**Changes Proposed in PR**: This PR will move the [F5Networks/charts](https://github.com/F5Networks/charts) source code to CIS repository.  [F5Networks/charts](https://github.com/F5Networks/charts) repo will only be used for publishing the charts. With these changes Azure Pipeline will publish the charts to ["incubator"](https://github.com/F5Networks/charts/tree/master/incubator) directory in charts for any changes in master branch and for any tag containing patterns v.x.x.x will publish the charts in [stable](https://github.com/F5Networks/charts/tree/master/stable) directory. This PR also include the changes for creating the CIS operator for testing purpose.  

## General Checklist
- [x] Updated the documentation

### CODE REVIEW

**Review by agupta49 — APPROVED** [review]
Looks fine

**Review by lavanya-f5 — APPROVED** [review]
LGTM

**Review by subbuv26 — APPROVED** [review]
Looks Good

**Pull request merged**
