### PR TITLE
Compatibility Matrix

### PR DESCRIPTION
**Pull request by charanm08**
**Description**: Update Compatibility Matrix

**Changes Proposed in PR**: Update Compatibility Matrix

**Fixes**: resolves #_Github issue id_

## General Checklist
- [x] Updated Added functionality/ bug fix in release notes
- [x] Added examples for new feature
- [x] Updated the documentation
- [x] Smoke testing completed

## CRD Checklist
- [x] Updated required CR schema

### CODE REVIEW

**Comment by vklohiya** [comment]
@charanm08 , Changes are already addressed in https://github.com/F5Networks/k8s-bigip-ctlr/pull/2694

**Review by nandakishorepeddi — APPROVED** [review]
LGTM

**Comment by charanm08** [comment]
Closing this PR as Changes are already addressed in https://github.com/F5Networks/k8s-bigip-ctlr/pull/2694

**Pull request closed without merging**
