### PR TITLE
Add HTTP client metrics

### PR DESCRIPTION
**Pull request by mikejoh**
**Description**:
We've been troubleshooting the `k8s-bigip-ctlr` from time to time the last six months and one thing we've been missing is metrics from the controller itself. By reusing the HTTP client instrumentation in the [`promhttp`](https://pkg.go.dev/github.com/prometheus/client_golang/prometheus/promhttp) package it's easy to compose a chain of metric middlewares (kind of) on the `http.Client` transport. 

We're running the exact same code in-house and it does give us some handy metrics when troubleshooting. It's easy to extend the use case and add alerting on e.g. certain status codes or duration of certain operations performed by the `http.Client`.

The metrics we get out of this PR is the following:
```
bigip_http_client_api_requests_total
bigip_http_client_dns_duration_seconds_bucket
bigip_http_client_dns_duration_seconds_count
bigip_http_client_dns_duration_seconds_sum
bigip_http_client_in_flight_requests
bigip_http_client_request_duration_seconds_bucket
bigip_http_client_request_duration_seconds_count
bigip_http_client_request_duration_seconds_sum
bigip_http_client_tls_duration_seconds_bucket
bigip_http_client_tls_duration_seconds_count
bigip_http_client_tls_duration_seconds_sum
```

There might be things to discuss here:
* Does the metrics have a good name?
* Do we need all of them?
* Right now there's no label splitting on e.g. the BIGIP URL, might be needed?
* Have i covered all `http.Client`s throughout the code base? There's two places i added the middleware chaining to the transport used by the HTTP client and that was in:
  * `pkg/agent/as3/postManager.go`
  * `pkg/controller/postManager.go`
  The latter one was the one in use, AFAICT, i'm unsure about the differences atm.

Also note that i have a bunch of smaller changes included in here due to mainly me running `go fmt`.

I could definitely spend more time with this PR if needed, part of the reason why i created this is to discuss if it's a good idea or not!  

**Changes Proposed in PR**:
* Addition of HTTP client metrics
* A configuration option to toggle these HTTP client metrics on and off

**Fixes**: 
N/A

## General Checklist
- [x] Updated Added functionality/ bug fix in release notes
- [x] Added examples for new feature
- [x] Updated the documentation
- [x] Smoke testing completed

## CRD Checklist
- [x] Updated required CR schema

### CODE REVIEW

**Comment by trinaths** [comment]
@mikejoh What is the usecase/issue this fix resolves ? Is this fix required for Prometheus monitoring or git pipelines ?

**Comment by trinaths** [comment]
Created [CONTCNTR-3794] for internal tracking.

**Review by vklohiya — APPROVED** [review]
LGTM

**Pull request merged**
