### PR TITLE
Add UID and ResourceVersion checks to avoid duplicate updates.

### PR DESCRIPTION
**Pull request by zongzw**
**Description**:  

This PR is to fix the misuses to `AddFunc` `UpdateFunc` `DeleteFunc` of `ResourceEventHandlerFuncs`.

**Changes Proposed in PR**:

Because of periodic resync strategy of client-go informer, there are lots of resync events happening after every periodic interval. We need to avoid this event noises, by using `UID` and `ResourceVersion` to filter real events.

**Fixes**: 
No Issue ID, but performance related.

## General Checklist
- [ ] Updated Added functionality/ bug fix in release notes
- [ ] Added examples for new feature
- [ ] Updated the documentation
- [ ] Smoke testing completed

## CRD Checklist
- [ ] Updated required CR schema

### CODE REVIEW

**Comment by zongzw** [comment]
Performance chart:

图片

**Comment by zongzw** [comment]
The performance test comparison: 
图片

**Comment by zongzw** [comment]
Performance test comparison:
图片

**Comment by trinaths** [comment]
Created [CONTCNTR-3200] for internal tracking.

**Comment by trinaths** [comment]
Inactive PR.

**Pull request closed without merging**
