### PR TITLE
Use informer for tuning resource deployment performance

### PR DESCRIPTION
**Pull request by zongzw**
**Description**: 

This PR is used to tuning performance of as3 mode for configmaps.

**Changes Proposed in PR**:

The main change in this PR is `func (appMgr *Manager) getEndpoints(selector, namespace string) []Member {` in `pkg/appmanager/appManager.go`

The way of getting endpoints is changed from `kubeclient` to `informer.cache`.

**Fixes**: No issue ID, but for performance.

**ToDo**: 

The hubMode situation is not covered in this PR.

## General Checklist
- [ ] Updated Added functionality/ bug fix in release notes
- [ ] Added examples for new feature
- [ ] Updated the documentation
- [ ] Smoke testing completed

## CRD Checklist
- [ ] Updated required CR schema

### CODE REVIEW

**Comment by zongzw** [comment]
Performance test result:

图片

**Comment by trinaths** [comment]
Created [CONTCNTR-3240] for internal tracking.

**Review by subbuv26 — CHANGES_REQUESTED** [review]

**Comment by zongzw** [comment]
You may close it, because it waited too long time to review, is it? From 15 Mar still now, 3 months.
Per this change request, using informer is the right way to do the search, however, CIS did so bad in this aspect. See the performance chart for the proof.

**Comment by subbuv26** [comment]
@zongzw please close this PR as it seems the other PR #2322 from @Niklaus-xie addresses the same performance issue and it got merged into master.

**Pull request closed without merging**
