### PR TITLE
Add Cilium CNI for static route mode

### LINKED ISSUE #2861: RFE: add static route mode support for Cilium CNI
#### Title
Title of the feature/enhancement request
add static route mode support for Cilium CNI

#### Description
A small overview of the feature/enhancement proposed

User has Cilium in route mode and BIG-IP is able to reach Cilium pod through static route

#### Actual Problem

BIG-IP is unable to reach to Cilium pod when Cilium in route mode and user does not want to use VXLAN in cluster mode

#### Solution Proposed

add static mode for Cilium CNI

### PR DESCRIPTION
**Pull request by vincentmli**
**Description**:  _Add Issue/Feature description_
https://github.com/F5Networks/k8s-bigip-ctlr/issues/2861

**Changes Proposed in PR**:
add Cilium node annotation detection in static route mode

**Fixes**: resolves #2861 
## General Checklist
- [x] Updated Added functionality/ bug fix in release notes
- [x] Added examples for new feature
- [x] Updated the documentation
- [x] Smoke testing completed

## CRD Checklist
- [x] Updated required CR schema

### CODE REVIEW

**Review by lavanya-f5 — APPROVED** [review]
LGTM

**Review by nandakishorepeddi — APPROVED** [review]
LGTM

**Comment by nandakishorepeddi** [comment]
Hi @vincentmli , Good Day! Please rebase the master with your latest changes in your good time. Will merge this PR.

**Comment by trinaths** [comment]
Created [CONTCNTR-3947] for internal tracking.

**Pull request merged**
