### PR TITLE
CCCL incompatible with BIG-IP v11.6.1 policies

### PR DESCRIPTION
**Pull request by edarzins**
Incompatibility with policy rules fixed in f5-sdk 3.0.3, update
requirements to point to new CCCL version.

### CODE REVIEW

**Comment by f5gary** [comment]
I think this commit should include an update to the attributions information, and probably a release note.

**Comment by sjberman** [comment]
Yes, forgot that we wanted to include this in the release notes.

**Comment by edarzins** [comment]
This was never broken in a release, only on "master" -- k8s v1.2 didn't have this bug.

**Comment by sjberman** [comment]
Ah, I had thought this was an issue in the release, but you're right!

**Comment by edarzins** [comment]
Where is the attribution info?

**Comment by f5gary** [comment]
Try running "make docs" in your repo. I see the travis build does run that step, but I don't understand why it passes - I expect it to fail when the CCCL SHA changes since it is a dependency.

**Comment by edarzins** [comment]
I ran 'make docs' and it created the correct attributions info for CCCL and the f5-sdk.

**Comment by f5gary** [comment]
Alright, I guess there's nothing else left to do.

**Pull request merged**
