### PR TITLE
Updating the crypto and protobuf packages

### PR DESCRIPTION
**Pull request by vklohiya**
**Description**:  Updating the crypto and protobuf packages

## General Checklist
- [ ] Updated Added functionality/ bug fix in release notes
- [ ] Added examples for new feature
- [ ] Updated the documentation
- [ ] Smoke testing completed

### CODE REVIEW

**Review by arzzon — APPROVED** [review]
LGTM

**Comment by vklohiya** [comment]
Closing the PR, as already merged.

**Pull request closed without merging**
