### PR TITLE
add-appManager-error-handle: Add error handle

### PR DESCRIPTION
**Pull request by yuchizh**
**Description**:  _Add Issue/Feature description_

**Changes Proposed in PR**:

**Fixes**: resolves #_Github issue id_

## General Checklist
- [ ] Updated Added functionality/ bug fix in release notes
- [ ] Added examples for new feature
- [ ] Updated the documentation
- [ ] Smoke testing completed

## CRD Checklist
- [ ] Updated required CR schema

### CODE REVIEW

**Comment by trinaths** [comment]
@yuchizh Please update the  PR template so the we can understand the issue/fix properly.

**Comment by trinaths** [comment]
@yuchizh Please also submit duly signed F5 Contributor agreement required for all external contributors.

**Comment by vklohiya** [comment]
Hi @yuchizh  Can you please sign the CLA it is required to accept CLA before committing any changes to k8s-bigip-ctlr repository . Attached the CLA document for your reference. Please sign and send to [containerconnector_cla@f5.com](mailto:containerconnector_cla@f5.com) and [c.jakkidi@f5.com](mailto:c.jakkidi@f5.com)
[CIS-F5 Contributor License Agreement.docx](https://github.com/F5Networks/k8s-bigip-ctlr/files/9973349/CIS-F5.Contributor.License.Agreement.docx)

**Comment by vklohiya** [comment]
Fixed as part of PR: https://github.com/F5Networks/k8s-bigip-ctlr/pull/2961

**Pull request closed without merging**
