### PR TITLE
Add namespace checking when validating to match controller configuration.

### LINKED ISSUE #1185: K8s unexpected across namespace monitor (AS3)
#### Description
I deployed two ingresses with configmap into two namespaces, and then I deployed two CIS to monitor the two namespaces separately, it works well. one cis watch one namespace.

But when I deploy another ingress with configmap+AS3 in the third namespace, and no CIS was configured to watch the third namespace. The two CIS both watch the AS3 deployment and configure the LTM, it is an unexceptional behavior.

Maybe it is a bug, pls check!

Kubernetes Version
v1.9.0

Controller Version
v1.12

BIG-IP Version
v13.1.1.5

### PR DESCRIPTION
**Pull request by wangzheng**
Fix #1185: AS3 manager now treat namespace isolation.

Problem: AS3 Informers are attached to all namespaces, regardless of how the Controller is configured. Thus, it will react on any AS3 related stuff even they're in another namespace that the controller should not deal with.

Solution: Perform an additional namespace checking when validating ConfigMap, Service and Endpoint.

### CODE REVIEW

**Comment by trinaths** [comment]
@wangzheng  please rebase to master and sqash multiple commits to 1 and update this PR.

**Comment by wangzheng** [comment]
@trinaths I rebased to master and squashed the commits to 1, please review this.

**Comment by trinaths** [comment]
Please raise this PR to 1.x-maintenance branch.

**Comment by trinaths** [comment]
@wangzheng - CIS 2.0 resolves this issue. Please close the PR.

**Comment by trinaths** [comment]
Closing this PR due to inactivity.

**Pull request closed without merging**
