### PR TITLE
HubMode support for configmaps

### PR DESCRIPTION
**Pull request by sravyap135**
**Description**: Multiple and Single Namespace support for Configmap 

**Changes Proposed in PR**: 
* Added new configuration parameter in CIS deployment `hubmode`
* Rewrites periodic-sync-interval to 30seconds when in hubmode 
* ConfigMap services can reside in unwatched namespaces ; endpoints will be updated dynamically when in cluster mode  

**Fixes**: JIRA CONTCNTR-2758 

## General Checklist
- [x] Updated Added functionality/ bug fix in release notes
- [x] Added examples for new feature
- [x] Updated the documentation

### CODE REVIEW

**Review by subbuv26 — APPROVED** [review]
LGTM

**Review by agupta49 — APPROVED** [review]

**Comment by sravyap135** [comment]
Fixed CONTCNTR-2763. Added case to handle namespace re-addition while enqueueing namespace.

**Pull request merged**
