### PR TITLE
IPAM controller hash update with latest commit

### PR DESCRIPTION
**Pull request by agupta49**
**Description**: IPAM controller hash update with latest commit

**Changes Proposed in PR**:

**Fixes**: resolves #_Github issue id_

## General Checklist
- [x] Updated Added functionality/ bug fix in release notes
- [x] Added examples for new feature
- [x] Updated the documentation

## CRD Checklist
- [x] Updated required CR schema

### CODE REVIEW

**Review by subbuv26 — APPROVED** [review]
LGTM

**Review by vklohiya — APPROVED** [review]
Looks Fine

**Pull request merged**
