### PR TITLE
Support Path based Routing for Reencrypt routes

### PR DESCRIPTION
**Pull request by veeramalla-f5**
Problem:
CIS does not support Path based routing for Reencrypt routes.

Solution:
Support Path based Routing for Reencrypt routes.

Affected Branches:
master

### CODE REVIEW

**Comment by trinaths** [comment]
Can you check the New Unit tests. they are hitting the error.

**Comment by ssurenr** [comment]
Since we modified the iRule, let's run a regression on both modes before we merge this.

**Comment by ssurenr** [comment]
@veeramalla-f5 Could you add a bugfix note in release notes under "next-release" section?

**Comment by veeramalla-f5** [comment]
Sure surendhar, Regression is in progress. I will also add the release notes.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by veeramalla-f5** [comment]
Regression passed in Cluster mode. Waiting for the results in Nodeport Mode.

**Comment by veeramalla-f5** [comment]
> A new bug is introduced where passthrough and re-encrypt annotation combination routes are not getting traffic with these changes.

This is resolved with new commit. Now we are handling Passthrough in TCP layer and Reencrypt in SSL layer.

**Comment by veeramalla-f5** [comment]
Regression passed in both Cluster and NodePort Mode.

**Pull request merged**
