### PR TITLE
Support for TS resource Profiles using PolicyCRD

### PR DESCRIPTION
**Pull request by nandakishorepeddi**
**Description**:  _Add Issue/Feature description_

**Changes Proposed in PR**:

**Fixes**: resolves #_Github issue id_

## General Checklist
- [x] Updated Added functionality/ bug fix in release notes
- [x] Added examples for new feature
- [x] Updated the documentation

## CRD Checklist
- [x] Updated required CR schema

### CODE REVIEW

**Review by agupta49 — APPROVED** [review]
LGTM

**Comment by nandakishorepeddi** [comment]
Closing as there is another PR which addresses the same: https://github.com/F5Networks/k8s-bigip-ctlr/pull/2079

**Pull request closed without merging**
