### PR TITLE
added missing httpTraffic description

### PR DESCRIPTION
**Pull request by rgarcia89**
**Description**:  Added missing httpTraffic definition for Virtual and Transport Server CRD 

**Changes Proposed in PR**:

**Fixes**: #_Github issue id_

## General Checklist
- [ ] Updated Added functionality/ bug fix in release notes
- [ ] Added examples for new feature
- [ ] Updated the documentation

## CRD Checklist
- [ ] Updated required CR schema

### CODE REVIEW

**Comment by trinaths** [comment]
@rgarcia89 - Thank you for the contribution. Please submit [F5 CLA](https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/CONTRIBUTING.md#contributor-license-agreement) for considering your contributions.

**Comment by rgarcia89** [comment]
> @rgarcia89 - Thank you for the contribution. Please submit [F5 CLA](https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/CONTRIBUTING.md#contributor-license-agreement) for considering your contributions.

Mail with signed Contributor License Agreement is on its way.
Thanks

**Comment by trinaths** [comment]
@rgarcia89 - Please rebase this PR and resubmit. New file location - https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/docs/config_examples/customResource/CustomResource.md

**Review by sravyap135 — COMMENTED** [review]
Please rebase this PR and I can approve and trigger pipeline

**Pull request closed without merging**
