### PR TITLE
Added debugging flags to Go build process 2.x-master

### PR DESCRIPTION
**Pull request by p-maha**
…4851)

**Description**:  Added debugging flags to Go build process with -gcflags="all=-N -l (#4851)

**Changes Proposed in PR**:

**Fixes**: resolves #4851

## General Checklist
- [x] Updated Added functionality/ bug fix in release notes
- [x] Added examples for new feature
- [x] Updated the documentation
- [x] Smoke testing completed

## CRD Checklist
- [x] Updated required CR schema

### CODE REVIEW

**Review by vklohiya — APPROVED** [review]
LGTM

**Comment by chandrajr** [comment]
Plese complete the pre checks before merge request review 
 Updated Added functionality/ bug fix in release notes
 Added examples for new feature
 Updated the documentation
 Smoke testing completed

**Review by arzzon — APPROVED** [review]
LGTM

**Pull request merged**
